FROM debian:wheezy
RUN apt-get update && apt-get install -y make autoconf automake libtool mingw32 mingw-w64 libc6-dev-i386
RUN apt-get install -y openjdk-7-jdk maven
RUN apt-get install -y git
RUN apt-get install -y gawk
